### ISSUE TITLE
Production : Instructor - Upload questions Please remove scroll bar from right side 

### ISSUE THREAD

**Issue by alpeshrpatel** [alpeshrpatel/gotestli-web#151]
![Uploading Screenshot 2024-11-22 at 4.12.20 PM.png…]()

**Comment by alpeshrpatel** [comment]
![Screenshot 2024-11-22 at 4 12 20 PM](https://github.com/user-attachments/assets/0c77d107-b6f6-45fd-9911-f5f07ecb68b9)

**Comment by Djkarmur** [comment]
done
